version: '3.4'

services:
  postgres:
    container_name: inventory_db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory
      POSTGRES_PASSWORD: inventory

volumes:
  postgres_data: